import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NextAuthSessionProvider from "@/Providers/NextAuthSessionProvider";
import ChatButton from "./component/ChatButton/ChatButton";
import { Toaster } from "sonner";
import Navbar from "./component/Navbar/Navbar";
import Footer from "./component/Footer/Footer";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
	const { locale } = await params;
	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}
	return (
		<html lang={locale}>
			<NextAuthSessionProvider>
				<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
					<NextIntlClientProvider>
						<Navbar></Navbar>
						<Toaster richColors closeButton />
						{children}
						<ChatButton />
						<Footer></Footer>
					</NextIntlClientProvider>
				</body>
			</NextAuthSessionProvider>
		</html>
	);
}
